models:
  - type: main
    engine: openai
    model: ddeepseek-ai/DeepSeek-R1
    api_key_env_var: HF_TOKEN
    parameters:
      base_url: https://router.huggingface.co/v1
      max_tokens: 512
      temperature: 0.1

  - type: embeddings
    engine: SentenceTransformers
    model: NeuML/bioclinical-modernbert-base-embeddings
